### ISSUE TITLE
Activity 2.1 Task #8 

### ISSUE THREAD

**Issue by mennengm** [STA518-01-Fall20/community#17]
I'm having issues finding which STEM majors have incomes less than the median income of all majors.

Code chunk:

```{r stem_low_salaries}
college_recent_grads %>%
  filter(stem_categories, median > 36000) %>%
  select(major, p25th, median, p75th)
```
Error: Problem with `filter()` input `..1`. x Input `..1` must be of size 173 or 1, not size 4. ℹ Input `..1` is `stem_categories`.

**Comment by dykesb** [comment]
The error is pointing to `stem_categories` because you do not currently specify how you want to use this information to `filter()`. When using `filter()` you need to specify a logical statement. One way to think of logical statements in `filter()` is using this template: `<variable> <operator> <level(s)>`

You did this correctly with the `median > 36000`: `<variable>` is `median`, `<operator>` is `>`, and `level` is `36000`.

My hint is that `stem_categories` are the `level(s)` component so now you need to think about which variable in `college_recent_grads` and [`<operator>`](https://r4ds.had.co.nz/transform.html#logical-operators) to use.
